name: ayunHideAndSeek
version: 1.0
main: me.ayunami2000.ayunHideAndSeek.Main
commands:
  hnsadmin:
    description: Control ayunHideAndSeek
    usage: /<command>
    permission: ayunhideandseek.admin
  hnsjoin:
    description: Join a hide and seek game!
    usage: /<command>
  hnsleave:
    description: Leave a hide and seek game!
    usage: /<command>
  hnsinfo:
    description: Get info about the current hide and seek game!
    usage: /<command>